### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by flipcasa** [HiDeoo/starlight-openapi#38]
### Describe the bug

Named export 'Parser' not found. The requested module 'parse5' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'parse5';
const { Parser, Token, TokenizerMode, html: html$3 } = pkg;

### To Reproduce

on astro build --root docs-ui

### Expected behavior

on running build its throwing error

on serve working file

### How often does this bug happen?

Every time

### Additional Context

Stack trace:
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:144:21)
    at async ModuleLoader.import (node:internal/modules/esm/loader:461:24)
    at async generatePages (node_modules/.pnpm/astro@4.11.5_@types+node@20.14.9_less@4.1.3_stylus@0.59.0_typescript@5.4.5/node_modules/astro/dist/core/build/generate.js:119:7)
    at async AstroBuilder.build (node_modules/.pnpm/astro@4.11.5_@types+node@20.14.9_less@4.1.3_stylus@0.59.0_typescript@5.4.5/node_modules/astro/dist/core/build/index.js:133:5)
    at async build (node_modules/.pnpm/astro@4.11.5_@types+node@20.14.9_less@4.1.3_stylus@0.59.0_typescript@5.4.5/node_modules/astro/dist/core/build/index.js:45:3)

**Comment by flipcasa** [comment]
installed parser5 and issue got resolved
